Repository NewSpring/Rock, pull requests merged in 2020-10, with the labels that each got.

#1141 added service note attribute value to service times data shortcode
  RockWeb/Themes/NewSpring/assets/Lava/DATA/service-times.lava
Labels: merge

#1106 Add Campus Events to NewSpring.cc
  RockWeb/Blocks/Event/CalendarLava.ascx.cs
  RockWeb/Themes/Fuse/Styles/checkin-theme.css
  RockWeb/Themes/KidSpring/Styles/checkin-theme.css
  RockWeb/Themes/NewSpring/Styles/_forms.less
  RockWeb/Themes/NewSpring/assets/Lava/Calendar.lava
  RockWeb/Themes/NewSpring/assets/Lava/CalendarItem.lava
  RockWeb/Themes/NewSpring/assets/Lava/LAYOUT/events-detail.lava
  RockWeb/Themes/NewSpring/assets/Lava/UI/events-list-campus.lava
  RockWeb/Themes/NewSpring/assets/Lava/UI/events-list.lava
  RockWeb/Themes/NewSpring/assets/Lava/UI/locations-events.lava
  RockWeb/Themes/NewSpring/assets/Lava/UI/side-by-side-new.lava
  RockWeb/Themes/NewSpring/assets/Lava/UI/swiper.lava
Labels: ready for review

#1145 Updated editorial detail template to display 'subscribe' UI on devos
  RockWeb/Themes/NewSpring/assets/Lava/LAYOUT/editorial-detail.lava
Labels: hacktoberfest-accepted, merge

#1147 Updated content lava templates to correctly 404 when an associated content Item is not passed in correctly, and to also not write an interaction
  RockWeb/Themes/NewSpring/assets/Lava/LAYOUT/collection-detail.lava
  RockWeb/Themes/NewSpring/assets/Lava/LAYOUT/editorial-detail.lava
  RockWeb/Themes/NewSpring/assets/Lava/LAYOUT/sermon-detail.lava
Labels: merge

#1149 Add Mergify
  .mergify.yml
Labels: merge

#1153 Make the Mergify Config Better
  .mergify.yml
Labels: merge

#1155 Added changes to giving history lava template to give access to business transactions
  RockWeb/Themes/NewSpring/assets/Lava/LAYOUT/giving-history.lava
Labels: merge
